language: ruby
rvm:
  - 2.1
env:
  global:
    - GIT_AUTHOR_EMAIL='tosainu.maple@gmail.com'
    - GIT_AUTHOR_NAME='Tosainu@travis-ci'
    - GIT_COMMITTER_EMAIL='tosainu.maple@gmail.com'
    - GIT_COMMITTER_NAME='Tosainu@travis-ci'
    - secure: BzrNsbGNrGKmeIO7S4SdPn6JXs+SDQOKqTjA0ck4IJJ8lqlgqhMTP5CeuNQsCeeiBe5R+DZHFPwcVwvPocUF9QdhI8SfnZUsNBIgTtmyp0urQpmqQFM9zbCxffYi7Qnp76Vy+Bdp6qZhX8kEXqNKRHXGL/kJYcZSlN7T3dmCtyw=
before_script:
  - git clone --quiet -b gh-pages https://github.com/Tosainu/blog build
script:
  - bundle exec middleman build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && bundle exec middleman deploy >/dev/null 2>&1'
