sudo: false
dist: trusty

language: generic

env:
  global:
    - secure: "Xu1MkJQb95pkBOhRFJKn20zGe81SR1zbYoTMNATB6YmM5VOQqkjQCnp66tqbUkuxapIU2/vSDXRJZH9PVd1eEAy2DfK8mjUQnRJmqq5c1hm4wwcQttWDwrLPrRDLy/oEunH+SnSa3oID3fiXddSzPaxA/rb1sIyYrUEMgtfOkdo="

install:
  - |
    mkdir -p ~/.local/bin
    export PATH=$HOME/.local/bin:$PATH
  - |
    travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz | \
      tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    stack --version
  - |
    nvm install 10.7.0
    nvm use 10.7.0

before_script:
  - |
    echo -e "flags:\n  hakyll:\n    previewServer: false\n    watchServer: false" >> stack.yaml
  - |
    stack --no-terminal --install-ghc setup
    stack --no-terminal exec ghc -- --version

jobs:
  include:
    - stage:  build cabal
      script: stack --no-terminal build -j 1 Cabal
    - stage:  build pandoc
      script: travis_wait 45 stack --no-terminal build pandoc
    - stage:  build other dependencies
      script: stack --no-terminal build  --only-dependencies

    - stage: deploy site
      script:
        - |
          set -ex

          # install NPM packages
          npm ci

          # build site generator
          stack --no-terminal build

          # build site
          git fetch origin gh-pages
          git worktree add --no-checkout build -b gh-pages FETCH_HEAD
          stack --no-terminal exec blog build

          set +ex
      after_success:
        - |
          if [[ "$TRAVIS_BRANCH" != "master" || "$TRAVIS_PULL_REQUEST" != "false" || "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
            exit 0;
          fi

          # setup deploy key
          declare -r SSH_FILE="$HOME/.ssh/github_deploy_key"
          openssl aes-256-cbc -K $encrypted_b46c1c70c077_key -iv $encrypted_b46c1c70c077_iv \
            -in "github_deploy_key.enc" -out "$SSH_FILE" -d
          chmod 600 "$SSH_FILE"
          echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ${SSH_FILE}\n\tIdentitiesOnly yes\n" \
            >> ~/.ssh/config

          git remote set-url --push origin 'git@github.com:Tosainu/blog.git'

          # deploy!
          cd build
          git add -A
          git commit --allow-empty --allow-empty-message -m ""
          git reset $(git commit-tree HEAD^{tree} -m "(✿╹◡╹)ﾉ")
          git push -f origin gh-pages

cache:
  directories:
    - $HOME/.stack
    - .stack-work
