# use container-based infrastructure
sudo: false
dist: trusty

# Ruby configuration
language: ruby
rvm:
  - 2.4.1
cache: bundler
bundler_args: --without development --jobs=3 --retry=3

env:
  global:
    - secure: "Xu1MkJQb95pkBOhRFJKn20zGe81SR1zbYoTMNATB6YmM5VOQqkjQCnp66tqbUkuxapIU2/vSDXRJZH9PVd1eEAy2DfK8mjUQnRJmqq5c1hm4wwcQttWDwrLPrRDLy/oEunH+SnSa3oID3fiXddSzPaxA/rb1sIyYrUEMgtfOkdo="

before_script:
  - git clone --quiet -b gh-pages https://github.com/Tosainu/blog build

script:
  - bundle exec middleman build

after_success:
  # setup deploy key
  - |
    if [[ "$TRAVIS_BRANCH" != "master" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      exit 0;
    fi

    declare -r SSH_FILE="$HOME/.ssh/github_deploy_key"
    openssl aes-256-cbc -K $encrypted_b46c1c70c077_key -iv $encrypted_b46c1c70c077_iv \
      -in "github_deploy_key.enc" -out "$SSH_FILE" -d
    chmod 600 "$SSH_FILE"
    echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ${SSH_FILE}\n\tIdentitiesOnly yes\n" \
      >> ~/.ssh/config

  # deploy!
  - bundle exec middleman deploy
